//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArduinoFileUploader.Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ArduinoFileUploader.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Breaks an error occurred while auto loading. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorMessage_AutoLoad {
            get {
                return ResourceManager.GetString("ErrorMessage_AutoLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Not specified target board. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorMessage_BordNotSpecified {
            get {
                return ResourceManager.GetString("ErrorMessage_BordNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   HEX file exceeds the load address. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorMessage_CodeTooLarge {
            get {
                return ResourceManager.GetString("ErrorMessage_CodeTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Send data does not exist. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorMessage_DataNotExist {
            get {
                return ResourceManager.GetString("ErrorMessage_DataNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Directory not found. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorMessage_DirectoryNotFound {
            get {
                return ResourceManager.GetString("ErrorMessage_DirectoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Running Worker Thread. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorMessage_RunningWorkerThread {
            get {
                return ResourceManager.GetString("ErrorMessage_RunningWorkerThread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Upload file is too large. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorMessage_UploadTooLarge {
            get {
                return ResourceManager.GetString("ErrorMessage_UploadTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   www.ooishoo.org に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HomePage {
            get {
                return ResourceManager.GetString("HomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   BoardName に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RegKey_BoardName {
            get {
                return ResourceManager.GetString("RegKey_BoardName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Software\ArduinoFileUploader に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RegKey_RootDir {
            get {
                return ResourceManager.GetString("RegKey_RootDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TargetAddress に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RegKey_TargetAddress {
            get {
                return ResourceManager.GetString("RegKey_TargetAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Version 0.22a に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
    }
}
